### ISSUE TITLE
Crear entidades MultiIdioma + IdiomaEntity

### ISSUE THREAD

**Issue by MNaveira7** [Borja-Aguiar/aperturas#2]
- [x] Crear Entidad idioma
- [x] Crear TipoProyectoIdioma
- [x] CrearEstadoLocalIdioma
- [x] CrearAlcanceObraIdioma
- [x] CrearEstadoProyectoIdioma

**Comment by Borja-Aguiar** [comment]
Completado

**Comment by fjregueiro** [comment]
Completado

**Comment by JGonzalezNovo** [comment]
Completado
